#!/usr/bin/env tsx
/**
 * Knowledge base builder for the Hub AI agent.
 * Reads all files in knowledge/ and generates netlify/functions/knowledge-data.ts
 *
 * Supported: .md, .txt, .mdx
 * PDFs: convert to .txt before adding to knowledge/
 * Runs automatically as prebuild step via package.json.
 */

import fs from 'fs'
import path from 'path'

interface Chunk {
  id: string
  source: string
  text: string
  keywords: string[]
}

const CHUNK_SIZE = 500
const CHUNK_OVERLAP = 50

const STOPWORDS = new Set([
  'the','a','an','and','or','but','in','on','at','to','for','of','with','by',
  'is','are','was','were','be','been','have','has','had','do','does','did',
  'will','would','could','should','may','might','shall','can','this','that',
  'these','those','it','its','as','from','not','no','so','if','then','than',
  'when','where','who','which','what','how','all','any','both','each','more',
  'most','other','some','such','only','own','same','too','very','just','about',
  'above','after','also','before','between',
])

function extractKeywords(text: string): string[] {
  return [
    ...new Set(
      text.toLowerCase()
        .replace(/[^a-z0-9\s]/g, ' ')
        .split(/\s+/)
        .filter(w => w.length > 2 && !STOPWORDS.has(w))
    ),
  ].slice(0, 60)
}

function chunkText(text: string, source: string): Chunk[] {
  const words = text.split(/\s+/).filter(Boolean)
  const result: Chunk[] = []
  let i = 0
  while (i < words.length) {
    const slice = words.slice(i, i + CHUNK_SIZE)
    const chunkText = slice.join(' ')
    result.push({ id: `${source}::${i}`, source, text: chunkText, keywords: extractKeywords(chunkText) })
    i += CHUNK_SIZE - CHUNK_OVERLAP
  }
  return result
}

function processFile(filePath: string, fileName: string): Chunk[] {
  const raw = fs.readFileSync(filePath, 'utf-8')
  const stripped = raw
    .replace(/^---[\s\S]*?---\n/, '')
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*|__|\*|_|`|~~|>/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim()
  return chunkText(stripped, fileName)
}

const knowledgeDir = path.join(process.cwd(), 'knowledge')
const outputDir  = path.join(process.cwd(), 'netlify', 'functions')
const outputFile = path.join(outputDir, 'knowledge-data.ts')

fs.mkdirSync(outputDir, { recursive: true })
if (!fs.existsSync(knowledgeDir)) fs.mkdirSync(knowledgeDir, { recursive: true })

const allChunks: Chunk[] = []
const EXTS = ['.md', '.txt', '.mdx']

const files = fs.existsSync(knowledgeDir)
  ? fs.readdirSync(knowledgeDir).filter(f => EXTS.includes(path.extname(f).toLowerCase())).sort()
  : []

for (const file of files) {
  const chunks = processFile(path.join(knowledgeDir, file), file)
  allChunks.push(...chunks)
  console.log(`  ✓ ${file} — ${chunks.length} chunks`)
}

fs.writeFileSync(outputFile, `// Auto-generated by scripts/build-knowledge.ts — do not edit manually
// Generated: ${new Date().toISOString()}
// Chunks: ${allChunks.length}

export interface Chunk {
  id: string
  source: string
  text: string
  keywords: string[]
}

export const chunks: Chunk[] = ${JSON.stringify(allChunks, null, 2)}
`)

console.log(`\nKnowledge store: ${allChunks.length} chunks → netlify/functions/knowledge-data.ts`)
